### PR TITLE
fix: correct typo

### PR DESCRIPTION
**Pull request by RafaelKr**
@timsuchanek I just fixed a little typo I found while sweeping through the last commits :)

### CODE REVIEW

**Comment by RafaelKr** [comment]
BTW: The CLA is out of date, it's still about Graphcool.

**Comment by timsuchanek** [comment]
Thanks for the PR ❤️

**Comment by RafaelKr** [comment]
You're welcome!

My comment about the CLA seems always to be overseen :stuck_out_tongue: Same here https://github.com/prisma/prisma2/pull/1229
Is your team aware of that?

**Comment by timsuchanek** [comment]
The actual company is still called Graphcool, so that's correct. But we should indeed still update the naming in the if possible.

**Pull request merged**
