### PR TITLE
docs(examples): remove comments and description from line 26

### PR DESCRIPTION
**Pull request by aliedp**
because in the last preview version its fixed and i removed that TODO description And Comment.
Thank you

### CODE REVIEW

**Comment by aliedp** [comment]
please merge this

**Comment by janpio** [comment]
Are the other 3 changes unrelated and only accidentally included in this PR?

**Comment by aliedp** [comment]
No, they have caused trouble.
i fixed Error : Property 'id' does not exist on type 'Params' with add => as { id: string }

**Comment by aliedp** [comment]
please merge this

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @aliedp 🙌

**Comment by aliedp** [comment]
you're welcome

I want to cooperate more

Because I love Prisma and want to use it in my products

**Pull request merged**
