### PR TITLE
graphql-auth examples - TypeError: definitions.trim is not a function

### PR DESCRIPTION
**Pull request by gihrig**
This PR presents a work around for: `TypeError: definitions.trim is not a function`.

**_Important: this solution only works with yarn - npm does not support the resolutions key_**

As a such, it is probably not appropriate to merge this PR, but this is a viable solution for yarn users.

The problem is triggered when `graphql-sheild` is enabled and `graphql-middleware@3.0.2` is installed. See graphql-middleware [#198](https://github.com/prisma/graphql-middleware/issues/198).

GraphQL Shield can be enabled  when `package.json` `resolutions` key specifies 

```json
"resolutions": {
  "graphql-middleware": "3.0.1"
}
```
If this resolution were merged into master, the READMEs would need to be modified to specify a dependency on yarn.

### CODE REVIEW

**Comment by timsuchanek** [comment]
Let's wait a bit until the bug is fixed. In case it's not fixed within the next week, we can merge this.

**Comment by timsuchanek** [comment]
@gihrig `graphql-middleware` has been updated with a fix. Can you upgrade to `graphql-middleware@3.0.3` in your PR, please?

**Comment by gihrig** [comment]
@timsuchanek `3.0.3` does not fix the issue.

@maticzav's fix was committed to branch `perf`. This is not included in `3.0.3`

image

**Comment by maticzav** [comment]
@gihrig @timsuchanek it’s the `switch to jest` branch

**Comment by gihrig** [comment]
@maticzav Ok, so I cloned and built the `jest` branch (`switch to jest` is a commit message) and this has corrected the error. When a tagged build is available, I'll be happy to update my PR, but...

@timsuchanek When there is a fixed version of graphql-middleware, why not just update graphql-yoga?

**Comment by maticzav** [comment]
@gihrig thank you for trying it out! Regarding `graphql-yoga`: it should auto update itself.

**Comment by janpio** [comment]
Is this PR still relevant then or can it be closed?

**Comment by gihrig** [comment]
This PR can be closed. The problem/solution properly exists at graphql-middleware [#198](https://github.com/prisma/graphql-middleware/issues/198).

**Pull request closed without merging**
